language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=travis

services:
  - mysql

before_script:
  - mysql -e 'create database baum_testing;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose
